returning items with the shape for shaped recipe
ShaneBeee/SkBee pull request #223
Opened 2022-07-27 05:23 UTC by MrEnxo

so instead of just getting the items when you try to get the ingredients of a recipe you also get the air and thus the shape of the shaped recipe

2022-07-27 05:44 UTC, ShaneBeee commented
I tried this before as a test, and it only works for custom recipes.
Vanilla recipes don't actually contain air or anything like that, its just the shape on how they're done.

2022-07-27 21:44 UTC, MrEnxo commented
thats weird... yea i have that same issue but i mean it works for now for custom recipes

2022-07-29 20:14 UTC, MrEnxo commented
I made a fix so it works with vanilla recipes now

2022-07-29 20:14 UTC, MrEnxo commented
@ShaneBeee

2022-07-29 20:15 UTC, ShaneBeee commented
> @ShaneBeee

you don't need to tag me, I get these on my discord and emails as well. 



> I made a fix so it works with vanilla recipes now

Awesome, I will give it a try and see how it goes

2022-07-29 20:17 UTC, MrEnxo commented
alright.

2022-07-29 20:20 UTC, MrEnxo commented
just added a patch to fix things!

2022-07-29 20:26 UTC, MrEnxo commented
currently this solution does not like any recipe with 9 items for some reason

2022-07-29 20:37 UTC, MrEnxo commented
this is now fixed

2022-07-29 20:44 UTC, ShaneBeee commented
this doesn't seem to work for small recipes, ie: jack o lantern (where its a 2x2 recipe)
<img width="966" alt="Screenshot 2022-07-29 at 1 42 58 PM" src="https://user-images.githubusercontent.com/20008482/181840328-c7fe07e1-a18a-40a0-9044-ce92b91a8bfc.png">

2022-07-29 20:47 UTC, MrEnxo commented
i mean it does get the shape but just not the right size for it... idk how we would solve this though

2022-07-29 20:48 UTC, ShaneBeee commented
> i mean it does get the shape but just not the right size for it... idk how we would solve this though

now you know why I never wanted to touch this haha

2022-07-29 20:48 UTC, MrEnxo commented
lolo

2022-07-29 20:50 UTC, ShaneBeee commented
WHAT IF... you checked the size of shape?
if its 2, that means its 2x2
if its 3, that means its 3x3
yeah?

2022-07-29 20:50 UTC, MrEnxo commented
hmmm maybe let me try that

2022-07-29 21:05 UTC, MrEnxo commented
IT WORKS!!!!

2022-07-29 21:08 UTC, ShaneBeee commented
good job.
Ok now... since both blocks of code are nearly identical, I feel like you could join them and just have vars set for the size
ex: `int i = size.length() + 1` <-- or some jazz like that

2022-07-29 21:09 UTC, MrEnxo commented
ig i could but im lazy but ill do it brb

2022-07-29 21:11 UTC, MrEnxo commented
alright done

2022-07-29 21:11 UTC, ShaneBeee commented
much better thanks, now let me test...

2022-07-29 21:18 UTC, ShaneBeee requested changes

2022-07-29 21:18 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/recipe/expressions/ExprIngredientsOfRecipe.java
> +
Everything looks good and works, now all I need you to do is remove these excessive blank lines please and thank you :)

2022-07-29 22:51 UTC, MrEnxo commented on src/main/java/com/shanebeestudios/skbee/elements/recipe/expressions/ExprIngredientsOfRecipe.java
> +
i have fix the blank lines

2022-07-29 23:04 UTC, ShaneBeee requested changes
Just a couple more nit picks from me. Sorry I didn't catch the two imports in the last review I did

2022-07-29 23:04 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/recipe/expressions/ExprIngredientsOfRecipe.java
> +import com.shanebeestudios.skbee.SkBee;
This import can be removed, Im assuming it was from when you were debugging.

2022-07-29 23:04 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/recipe/expressions/ExprIngredientsOfRecipe.java
> +import org.bukkit.Material;
I don't believe this import is being used either

2022-07-29 23:04 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/recipe/expressions/ExprIngredientsOfRecipe.java
> +
Sorry to be nitpicky but can you remove this blank line too please

2022-07-29 23:04 UTC, MrEnxo commented on src/main/java/com/shanebeestudios/skbee/elements/recipe/expressions/ExprIngredientsOfRecipe.java
> +
fixed*

2022-07-29 23:05 UTC, MrEnxo commented on src/main/java/com/shanebeestudios/skbee/elements/recipe/expressions/ExprIngredientsOfRecipe.java
> +
fixed the imports and the line. I thought I deleted that line, I guess not. Also material is a needed import

2022-07-29 23:06 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/recipe/expressions/ExprIngredientsOfRecipe.java
> +
oh yes. Material.AIR... duh ... I missed that. Thanks

2022-07-29 23:07 UTC, ShaneBeee approved these changes

2022-07-29 23:09 UTC, merged

2022-07-29 23:09 UTC, ShaneBeee commented
merged... thank you for your contribution :)