Add Temporary Bounds to Current Bound System
ShaneBeee/SkBee pull request #393
Opened 2023-05-18 19:33 UTC by DelayedGaming

This PR adds temporary bounds creation into SkBee, followed by a condition to check whether a bound is temporary.
Enhanced ExprBoundAllBounds to support for temporary bounds.

---
Related Issues: #355

2023-05-18 22:50 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/bound/conditions/CondBoundIsTemporary.java
> +        register(CondBoundIsTemporary.class, "temporary", "bound");
I do worry about this syntax, potentially colliding with something in the future.
Maybe `"[a] temporary bound"` .... so the example would be:
`if bound with id "test-bound" is a temporary bound:`

2023-05-18 23:43 UTC, Fusezion commented on src/main/java/com/shanebeestudios/skbee/elements/bound/conditions/CondBoundIsTemporary.java
> +        register(CondBoundIsTemporary.class, "temporary", "bound");
```suggestion
        register(CondBoundIsTemporary.class, "[a] temporary bound", "bound");
```

To make it a little easier if so

2023-05-19 00:44 UTC, DelayedGaming commented on src/main/java/com/shanebeestudios/skbee/elements/bound/conditions/CondBoundIsTemporary.java
> +        register(CondBoundIsTemporary.class, "temporary", "bound");
I reviewed on how SkBee is set up and attempts to adapt to it, and there aren't any syntax which supports plurals.
If any of you would like to have this condition support plural, do let me know

2023-05-19 00:46 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/bound/conditions/CondBoundIsTemporary.java
> +        register(CondBoundIsTemporary.class, "temporary", "bound");
maybe `"[a] temporary bound[s]"`

2023-05-19 01:35 UTC, DelayedGaming commented on src/main/java/com/shanebeestudios/skbee/elements/bound/conditions/CondBoundIsTemporary.java
> +        register(CondBoundIsTemporary.class, "temporary", "bound");
So plural it is!

2023-05-19 01:50 UTC, Fusezion commented on src/main/java/com/shanebeestudios/skbee/elements/bound/conditions/CondBoundIsTemporary.java
> +        register(CondBoundIsTemporary.class, "temporary", "bound");
If no plurals are supported rn it's something we should think about updating to support

2023-05-19 03:27 UTC, DelayedGaming commented on src/main/java/com/shanebeestudios/skbee/elements/bound/sections/EffSecBoundCreate.java
> +                "create [a] [new] [:temporary] [:full] bound with id %string% (within|between) %location% and %location%");
Do you think that reverse order of these 2 optional tags should be supported in the syntax?

2023-05-19 03:50 UTC, Fusezion commented on src/main/java/com/shanebeestudios/skbee/elements/bound/sections/EffSecBoundCreate.java
> +                "create [a] [new] [:temporary] [:full] bound with id %string% (within|between) %location% and %location%");
Eh `temporary full bound with id "blah"` rolls off my noggin better than `full temporary bound with id "blah"`
So I personally am against it and prefer it's current values

2023-05-19 16:29 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/bound/sections/EffSecBoundCreate.java
> +                "create [a] [new] [:temporary] [:full] bound with id %string% (within|between) %location% and %location%");
I agree that "temporary" should be first

2023-05-19 16:42 UTC, ShaneBeee requested changes
Just a few changes, some of which have already been discussed

2023-05-19 16:42 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/bound/conditions/CondBoundIsTemporary.java
> +        register(CondBoundIsTemporary.class, "a temporary bound", "bound");
as stated earlier:
```suggestion
        register(CondBoundIsTemporary.class, "[a] temporary bound[s]", "bounds");
```

2023-05-19 16:42 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/bound/expressions/ExprBoundAllBounds.java
> +        return (group.name().toLowerCase(Locale.ENGLISH).replaceFirst("_", " ")) + " bound" + (ID ? " ids" : "s" + (this.world != null ? " in world[s] " + this.world.toString(e, d) : ""));
this part:
`(group.name().toLowerCase(Locale.ENGLISH).replaceFirst("_", " "))`
really hurts my brain.
Rather than doing this, I recommend adding the name directly in the enum. 
ex: 
```java
private enum Group {

    ALL("all"),
    NON_TEMPORARY("non temporary"),
    TEMPORARY("temporary");

    private final String name;

    private Group(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
    
}
```
then you can do `group.getName()`

2023-05-19 16:42 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/bound/expressions/ExprBoundAllBounds.java
>  @Description("Get a list of all bounds, optionally in a specific world.")
Description should describe temporary bounds.

2023-05-20 15:34 UTC, Fusezion approved these changes

2023-05-22 17:02 UTC, ShaneBeee approved these changes

2023-05-22 17:05 UTC, merged

2023-05-22 17:05 UTC, ShaneBeee commented
Thank you for your contribution :)