Bounds - Preparations Update
ShaneBeee/SkBee pull request #413
Opened 2023-06-24 04:11 UTC by Fusezion

This pr is the start of #400 which includes the start to bounds enhancements. I have listed what I've done in this PR below along with what I want to finish adding before we go ahead and merge this.

- [x] ExitBoundEvent and EnterBoundEvent renamed to BoundExitEvent and BoundEnterEvent
- [x] BoundEvent super class added and above events extending it
- [x] Update to BoundEvents classes' event values 
- [x] Enhancements to the `ExprBoundAllBounds` and `ExprBoundAtLocation` classes
- [x] Config settings to change which events are checked by `BoundBorderListener`
- [x] Even more events added to `BoundBorderListener`
- [ ] plurals in some bound syntax
- [ ] Clone/Copy bound

2023-06-24 18:23 UTC, Fusezion commented
With only bound copy section being needed, I'm going ahead and marking this ready for review. Should hopefully finish this tonight if not tomorrow.

2023-07-07 16:08 UTC, ShaneBeee requested changes
just a few small changes then I think its good to go

2023-07-07 16:08 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/bound/expressions/ExprAllBounds.java
> +    }
simplify?!?!
```suggestion
    public @NotNull String toString(@Nullable Event event, boolean debug) {
        String ID = this.ID ? " ids" : "s";
        return switch (boundType) {
            case TRUE -> "all non-temporary bound";
            case FALSE -> "all temporary bound";
            case UNKNOWN -> "all bound";
        }  + ID;
    }
```

2023-07-07 16:08 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/bound/expressions/ExprBoundsAtLocation.java
> +    }
simplify again?!?!
```suggestion
    public @NotNull String toString(Event event, boolean debug) {
        String ID = this.ID ? " ids" : "s";
        String atLocation = " at " + locations.toString(event, debug);
        return switch (boundType) {
            case TRUE -> "all non-temporary bound";
            case FALSE -> "all temporary bound";
            case UNKNOWN -> "all bound";
        } + ID + atLocation;
    }
```

2023-07-07 16:08 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/bound/expressions/ExprBoundsInWorld.java
> +    }
one more time
```suggestion
    public String toString(@Nullable Event event, boolean debug) {
        String ID = this.ID ? " ids" : "s";
        String inWorld = " in world " + worlds.toString(event, debug);
        return switch (boundType) {
            case TRUE -> "all non-temporary bound";
            case FALSE -> "all temporary bound";
            case UNKNOWN -> "all bound";
        } + ID + inWorld;
    }
```

2023-07-07 16:08 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/bound/expressions/ExprLastCreatedBound.java
> +}
```suggestion
    }

}
```

2023-07-07 16:08 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/bound/sections/EffSecBoundCopy.java
> +@Description("Create an exact replica of an existing bound with a new id")
```suggestion
@Description("Create an exact replica of an existing bound with a new id.")
```

2023-07-08 18:56 UTC, merged

2023-09-01 19:24 UTC, sovdeeth commented on src/main/java/com/shanebeestudios/skbee/api/listener/BoundBorderListener.java
> -            }
Was this intended @Fusezion

2023-09-01 20:50 UTC, sovdeeth commented on src/main/java/com/shanebeestudios/skbee/api/listener/BoundBorderListener.java
> -            }
![image](https://github.com/ShaneBeee/SkBee/assets/10354869/4e2b67ba-98f6-47f3-b65c-a13f9ed917cb)
Seems to leave a useless listener