Recipes/recipe choice
ShaneBeee/SkBee pull request #423
Opened 2023-07-02 09:59 UTC by Fusezion

Start of recipe updates, RecipeChoice additions.

This PR adds support for ExactChoice, while updating some minor changes in syntax for readability and/or later use.

- Added error message when using SmithingRecipes on 1.20
  - Using the normal `new SmithingRecipe()` no longer works as intended and would just silently fail
  - Testing to see if this is paper only is needed, however you can't even place items in gui anyways
- Reworked MaterialChoice to use RecipeChoice to support ExactChoice
- Added expression to get choices of recipe choice, currently is limited in use until `ExprIngredientsOfRecipe` is changed to use RecipeChoice in a later pr. Additionally will need to decide if adding `random choice out of %recipechoice%` will be good in some format.
- Simplify effects to use new `getRecipeChoice/getExactChoice/getMaterialChoice` methods in `RecipeUtil` class removing unnecessary clutter 
- Updated Crafting and Cooking recipes to be split into seperate patterns for increased readability
  
![image](https://github.com/ShaneBeee/SkBee/assets/81952476/196d56d6-8798-4ff7-9e9e-28302d797378)

2023-07-02 16:01 UTC, ShaneBeee requested changes
just a few requested changes

2023-07-02 16:01 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/api/recipe/RecipeUtil.java
> +                if (isAir) continue;
could this just be one line?
```suggestion
                if (itemStack.getType().isAir()) continue;
```
same with the one bellow

2023-07-02 16:31 UTC, Fusezion commented on src/main/java/com/shanebeestudios/skbee/api/recipe/RecipeUtil.java
> +                if (isAir) continue;
I think this habit came from when I first redid these where the old code also split them all off into their own fields

2023-07-09 19:09 UTC, ShaneBeee requested changes
ok, this is all I could find

2023-07-09 19:09 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/recipe/effects/EffCookingRecipe.java
> +        Bukkit.broadcastMessage("" + matchedPattern);
Im assuming this was a debug?

2023-07-09 19:24 UTC, Fusezion commented on src/main/java/com/shanebeestudios/skbee/elements/recipe/effects/EffCookingRecipe.java
> +        Bukkit.broadcastMessage("" + matchedPattern);
Ah yes I'm at work so I'll fix it when I get off in 4 hours unless you want to

2023-07-09 19:25 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/recipe/effects/EffCookingRecipe.java
> +        Bukkit.broadcastMessage("" + matchedPattern);
yeah I can do it

2023-09-10 07:45 UTC, Fusezion commented on src/main/java/com/shanebeestudios/skbee/api/recipe/RecipeUtil.java
> +        if (object == null) return null;
Self reminder to update this to support `ItemType#getAll()`

2023-09-11 23:50 UTC, Fusezion commented
Closing this pr and deleting branch to swap to my fork and account for any new changes. Don't feel like handling conflicts either.

2023-09-11 23:50 UTC, closed without merging