Add Lockable block state
ShaneBeee/SkBee pull request #450
Opened 2023-07-20 22:28 UTC by Fusezion

Adds support for the lockable block state includes everything container and beacons

2023-07-20 23:34 UTC, ShaneBeee requested changes
just a few things

2023-07-20 23:34 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/other/conditions/CondIsLocked.java
> +@Description("Check if a container or beacon is in a locked state")
you and you damn periods
```suggestion
@Description("Check if a container or beacon is in a locked state.")
```

2023-07-20 23:34 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/other/conditions/CondIsLocked.java
> +@Examples({"on right click on shulker box or beacon",
```suggestion
@Examples({"on right click on shulker box or beacon:",
```

2023-07-20 23:34 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/other/conditions/CondIsLocked.java
> +        "send action bar \"%lock of clicked block%\" to player"})
```suggestion
        "\tsend action bar \"%lock of clicked block%\" to player"})
```

2023-07-20 23:34 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprLockableLock.java
> +@Description("Get or set the lock of a container or beacon")
```suggestion
@Description("Get or set the lock of a container or beacon.")
```

2023-07-20 23:34 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprLockableLock.java
> +@Examples({"on right click on shulker box or beacon",
```suggestion
@Examples({"on right click on shulker box or beacon:",
```

2023-07-20 23:34 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprLockableLock.java
> +        "send action bar \"%lock of clicked block%\" to player"})
```suggestion
        "\tsend action bar \"%lock of clicked block%\" to player"})
```

2023-07-20 23:34 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprLockableLock.java
> +        register(ExprLockableLock.class, String.class, "lock", "blocks");
this worries me for future conflicts... maybe "lock key"? or "lockable key" like your getPropertyName

2023-07-20 23:48 UTC, Fusezion commented on src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprLockableLock.java
> +        register(ExprLockableLock.class, String.class, "lock", "blocks");
ah yeah I used to have `[lockable] (key|lock)` but was unsure and just second guessed myself

2023-07-21 00:10 UTC, Fusezion commented on src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprLockableLock.java
> +        register(ExprLockableLock.class, String.class, "lock", "blocks");
Went a head and made syntax `(container|lockable) key` prevents any conflict and is a bit more readable than `lockable key`
I prefer `set container key of target block to "apple_pie"` over `set lockable key...`

2023-07-21 01:32 UTC, merged