Adds ExprNamespaceKeyOf
ShaneBeee/SkBee pull request #468
Opened 2023-08-09 02:08 UTC by Fusezion

Adds methods to get namespace and key from a namespacedkey value

2023-08-09 15:24 UTC, ShaneBeee requested changes
just a few changes

2023-08-09 15:24 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprNamespaceKeyOf.java
> +		register(ExprNamespaceKeyOf.class, String.class, "namespace [:key]", "namespacedkeys");
I feel like this should be:
```suggestion
		register(ExprNamespaceKeyOf.class, String.class, "(namespace|:key)", "namespacedkeys");
```

2023-08-09 15:24 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprNamespaceKeyOf.java
> +
not sure where to put this, so ill put this at the top
I noticed this class is using tabs not spaces

2023-08-09 15:24 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprNamespaceKeyOf.java
> +		key = parseResult.hasTag("key");
just for consistency sake with how ive been doing things
```suggestion
		this.key = parseResult.hasTag("key");
```

2023-08-09 15:24 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprNamespaceKeyOf.java
> +		return key ? namespacedKey.getKey() : namespacedKey.getNamespace();
same as above
```suggestion
		return this.key ? namespacedKey.getKey() : namespacedKey.getNamespace();
```

2023-08-09 15:24 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprNamespaceKeyOf.java
> +		return "namespace" + (key ? " key" : "");
```suggestion
		return this.key ? "key" : "namespace";
```

2023-08-09 20:42 UTC, Fusezion commented on src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprNamespaceKeyOf.java
> +		register(ExprNamespaceKeyOf.class, String.class, "namespace [:key]", "namespacedkeys");
I didn't do that due to `key of %namespacedkeys%`, this was the same issue we had with lockable keys

2023-08-09 20:42 UTC, Fusezion commented on src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprNamespaceKeyOf.java
> +
ah whoops sorry, my current project uses tabs forgot to swap back for this

2023-08-09 20:46 UTC, ShaneBeee commented on src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprNamespaceKeyOf.java
> +		register(ExprNamespaceKeyOf.class, String.class, "namespace [:key]", "namespacedkeys");
I don't know where that is used... that said, in my honest opinion, I don't think this expression is really needed.
Due to the fact that:
a) I can't see many people using it at all
b) you can easily stringily and split

2023-08-09 20:50 UTC, Fusezion commented on src/main/java/com/shanebeestudios/skbee/elements/other/expressions/ExprNamespaceKeyOf.java
> +		register(ExprNamespaceKeyOf.class, String.class, "namespace [:key]", "namespacedkeys");
It's not used anywhere but it's just in the case of a conflict between anything with `key` being the only thing that's gonna be used for matching *aside from literals*

2023-08-21 07:04 UTC, Fusezion commented
Gonna go ahead and just remove the namespace stuff, all that'll remain is the 2 commits you did for ExprDisplayViewRange.

2023-08-21 17:20 UTC, merged